### ISSUE TITLE
GLEW ERROR

### ISSUE THREAD

**Issue by Cozmikaos** [barotto/IBMulator#14] opened 2016-10-19 09:40 UTC
From the log

[ERR0] gui | GLEW ERROR: Missing GL Version

Running win7 ultimate under vmware 8 on osx elcapitan mac mini the open gl version for mac os 4.1 , open gl version for vmware is 3.3

Please help, thank you!

**Comment by barotto** [comment] 2016-10-22 21:23
Hi, can you run the program adding '-v 2' to the command line and then post the complete log?
Do other OpenGL programs work under vmware?

**Comment by Cozmikaos** [comment] 2016-10-23 04:27
[INF1] prg | Compiled against SDL version 2.0.3
[INF1] prg | Linking against SDL version 2.0.3
[INF0] prg | Calibrating... done
[INF0] cpu | Frequency: 10.000 MHz
[INF0] mem | Installed RAM: 1024KB (base: 640KB, extended: 384KB)
[INF0] mem | Loading ROM set 'C:\Users\Office\AppData\Local\ibmulator\PS1_2011_ROM.zip'
[INF0] mem | System model ID: 0xFC
[INF0] mem | BIOS version: 1057754 (C) COPYRIGHT IBM CORPORATION 1981, 1989 ALL RIGHTS RESERVED 
[INF0] mem | BIOS date: 12/01/89
[INF0] mem | BIOS type: PS/1 (LW-Type 44)
[INF0] hdd | Using image file 'C:\Users\Office\AppData\Local\ibmulator\hdd.img'
[INF0] hdd | Installed drive C as type 35 (29.7MiB)
[INF0] flp | Installed floppy A as 3.5 HD
[INF0] kbd | Installed PS/2 mouse
[INF0] lpt | Parallel port at 0x03BC (LPT1), irq 7, mode EXTENDED
[INF0] com | COM1 at 0x03f8, irq 4 (mode: null)
[ERR0] mix | Unable to find any audio device
[ERR0] mix | Failed to open audio: DirectSoundCreate: No audio device found
[ERR0] mix | wave audio output disabled
[INF0] gui | Selected video mode: 640x480
[ERR0] gui | GLEW ERROR: Missing GL version
[ERR0] prg | exception caught during initialization! giving up :(

**Comment by Cozmikaos** [comment] 2016-10-23 04:31
not sure if any other opengl 3.3 programs are working under vmware as i only installed this vm for ibmulator because parallels has no 3.3 support. is there a small program you could suggest that i can test out to see where the problem lies?

thank you once again!

**Comment by barotto** [comment] 2016-10-23 09:57
For some reason the Windows version doesn't report all the important data in the log file, like the video driver.
Use this program to get various OpenGL info: http://www.realtech-vr.com/glview/download.php
On the main window it should report a OpenGL version number of 3.3 or up for IBMulator to work properly.
If it reports version 1.1 or 1.2 it means that the video drivers are not properly installed.

**Comment by ZaDarkSide** [comment] 2017-11-22 02:53
This is still happening on Windows 10 Version 1703 Build 15063.726

Please check this thread:
https://stackoverflow.com/questions/14276444/failed-to-initialize-glew-missing-gl-version

**Comment by barotto** [comment] 2018-03-18 18:34
This is not happening for me on the latest Windows 10 for version 0.9 beta1, probably fixed in one of the latest couple hundred commits.
Closing because I can't reproduce.

**Closed by barotto** 2018-03-18 18:34 UTC
